apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "dev-repo-infra-infra"
  description: "Recursos de infraestrutura para a aplicação dev-repo-infra"
  links:
    - title: Repositório de Código
      url: "https://github.com/romagalhaes/dev-repo-infra"
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: "url:https://github.com/romagalhaes/dev-repo-infra-infra/tree/main/"
    github.com/project-slug: romagalhaes/dev-repo-infra-infra
    idp.mycompany.com/repository-role: infrastructure
spec:
  type: infrastructure
  owner: "group:default/guests"
  lifecycle: production
